# Generated by Django 6.0.6 on 2026-06-27 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.AutoField(primary_key=True, serialize=False)),
                ('especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id_pack', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'pack',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.IntegerField()),
            ],
            options={
                'db_table': 'servicio',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(default='Activa', max_length=20)),
                ('direccion_completa', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=150)),
                ('gps_latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('gps_longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
            ],
            options={
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=150, unique=True)),
                ('contrasenia', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=30)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='cuentas.cliente')),
                ('empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='cuentas.empleado')),
                ('pack', models.ForeignKey(db_column='id_pack', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.pack')),
                ('servicio', models.ForeignKey(db_column='id_servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.servicio')),
                ('sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='cuentas.sucursal')),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.CASCADE, to='cuentas.cita')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha', models.DateField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago', models.ForeignKey(db_column='id_pago', on_delete=django.db.models.deletion.CASCADE, to='cuentas.pago')),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id_postulacion', models.AutoField(primary_key=True, serialize=False)),
                ('puesto_aplica', models.CharField(max_length=100)),
                ('nombre_candidato', models.CharField(max_length=100)),
                ('correo_candidato', models.EmailField(max_length=150)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('portafolio_instagram', models.CharField(blank=True, max_length=150, null=True)),
                ('motivacion', models.TextField(blank=True, null=True)),
                ('cv_url', models.CharField(max_length=255)),
                ('fecha_postulacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='Recibido', max_length=30)),
                ('sucursal_interes', models.ForeignKey(db_column='id_sucursal_interes', on_delete=django.db.models.deletion.CASCADE, to='cuentas.sucursal')),
            ],
            options={
                'db_table': 'postulacion',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.CASCADE, to='cuentas.sucursal'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_notificacion', models.CharField(max_length=50)),
                ('asunto', models.CharField(max_length=150)),
                ('mensaje', models.TextField()),
                ('canal_difusion', models.CharField(max_length=50)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.usuario')),
            ],
            options={
                'db_table': 'notificacion',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='cuentas.usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='cuentas.usuario'),
        ),
    ]
