# Generated by Django 6.0.6 on 2026-06-27 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoWeb',
            fields=[
                ('id_contenido', models.AutoField(primary_key=True, serialize=False)),
                ('seccion', models.CharField(max_length=50)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitulo', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='web/')),
            ],
            options={
                'db_table': 'contenido_web',
            },
        ),
        migrations.CreateModel(
            name='LogSistema',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_correo', models.CharField(max_length=150)),
                ('accion', models.CharField(max_length=255)),
                ('modulo', models.CharField(max_length=50)),
                ('ip', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(default='INFO', max_length=20)),
            ],
            options={
                'db_table': 'log_sistema',
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='duracion',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='pack',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='estado',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AddField(
            model_name='servicio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='pack',
            field=models.ForeignKey(blank=True, db_column='id_pack', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.pack'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(blank=True, db_column='id_servicio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuentas.servicio'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id_resena', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(default=5)),
                ('comentario', models.TextField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='cuentas.cliente')),
            ],
            options={
                'db_table': 'resena',
            },
        ),
    ]
