# Generated by Django 6.0.6 on 2026-06-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_contenidoweb_logsistema_cita_total_empleado_cargo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioComplementario',
            fields=[
                ('id_complementario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_extra', models.IntegerField(default=15)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'servicio_complementario',
            },
        ),
    ]
