# Generated by Django 6.0.6 on 2026-07-12 18:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_configuracionsistema'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='foto',
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
